#!/usr/bin/python
# -*- coding: utf-8 -*-


from plugin import *
from siriObjects.systemObjects import ResultCallback
import uuid

class examplePlugin(Plugin):
    
    @register("de-DE", ".*Sinn.*Leben.*")
    @register("it-IT", ".*Significato.*Vita.*")
    def meaningOfLife(self, speech, language, matchedRegex):
        if language == 'de-DE':
            answer = self.ask(u"Willst du das wirklich wissen?")
            self.say(u"Du hast \"{0}\" gesagt!".format(answer))
        else:
            self.say("Non posso dirtelo!")
        self.complete_request()

    @register("de-DE", "(.*Hallo.*)|(.*Hi.*Siri.*)|(Hi)|(Hey)")
    @register("it-IT", "(.*Ciao.*)|(.*Ciao.*Siri.*)|(Ciao)|(Ei)")
    @register("fr-FR", ".*(Bonjour|Coucou|Salut)( Siri)?.*")
    @register("nl-NL", ".*(Hallo|Goeiedag|Heey)( Siri)?.*")
    def st_hello(self, speech, language):
        if language == 'de-DE':
            self.say(u"Hallo {0}!".format(self.user_name()))
        elif language == 'fr-FR':
            self.say(u"Bonjour {0}!".format(self.user_name()));
        elif language == 'nl-NL':
            self.say(u"Hallo, {0}!".format(self.user_name()));
        else:
            self.say(u"Ciao, {0}!".format(self.user_name()))
        self.complete_request()
    
    @register("de-DE", ".*standort.*test.*")
    @register("it-IT", ".*location.*test.*")
    @register("nl-NL", ".*locatie.*test.*")
    def locationTest(self, speech, language):
        location = self.getCurrentLocation(force_reload=True)
        self.say(u"lat: {0}, long: {1}".format(location.latitude, location.longitude))
        self.complete_request()
          
