#!/usr/bin/env python
# encoding: utf-8
"""
Mapping Plugins for SiriServerCore
Created by Javik
"""
import re
import urllib2, urllib
import json
from plugin import *
from siriObjects.systemObjects import *
from siriObjects.uiObjects import *
from siriObjects.localsearchObjects import MapItem, MapItemSnippet, ShowMapPoints
from siriObjects.uiObjects import AddViews, AssistantUtteranceView
from siriObjects.baseObjects import *
from siriObjects.contactObjects import *


class Mapping(Plugin):
	@register("it-IT", "(Dove si trova) (.*)")
	@register("en-GB", "((Where is) (.*))")
	def whereis(self, speech, language, regex):
	     self.say('Sto cercando...',' ')
	     Title = regex.group(regex.lastindex).strip()    
	     Query = urllib.quote_plus(str(Title.encode("utf-8")))
	     googleurl = "http://maps.googleapis.com/maps/api/geocode/json?address={0}&sensor=true&language=en".format(Query)
	     jsonString = urllib2.urlopen(googleurl, timeout=20).read()
	     response = json.loads(jsonString)
	     if (response['status'] == 'OK') and (len(response['results'])):
	       googleplaces_results = []
	       for result in response['results']:
	           label = "{0}".format(Title.title())
	           street =result['formatted_address']
	           latitude=result['geometry']['location']['lat']
	           longitude=result['geometry']['location']['lng']
           
	           mapitem = MapItem(label=label, street=street, latitude=latitude, longitude=longitude)
	           googleplaces_results.append(mapitem)
	           mapsnippet = MapItemSnippet(items=googleplaces_results)
	           view = AddViews(self.refId, dialogPhase="Completion")
	           view.views = [AssistantUtteranceView(speakableText='Ecco {0} sulla mappa...'.format(Title.title()), dialogIdentifier="googlePlacesMap"), mapsnippet]
	           self.sendRequestWithoutAnswer(view)
	           self.complete_request()
	     else:
	       self.say("Scusa, non ho trovato alcun luogo...")
	       self.complete_request()
       
	@register("it-IT", "(Dove sono.*)|(Dove siamo.*)")
	@register("en-GB", "(Where am I.*)|(Where are we.*)")
	def whereami(self, speech, language, regex):
	     self.say('Sto cercando...',' ')
	     mapGetLocation = self.getCurrentLocation(force_reload=True,accuracy=GetRequestOrigin.desiredAccuracyBest)
	     latitude= mapGetLocation.latitude
	     longitude= mapGetLocation.longitude
	     googleurl = "http://maps.googleapis.com/maps/api/geocode/json?latlng={0},{1}&sensor=true".format(latitude, longitude)
	     jsonString = urllib2.urlopen(googleurl, timeout=20).read()
	     response = json.loads(jsonString)
	     if (response['status'] == 'OK') and (len(response['results'])):
	       googleplaces_results = []
	       for result in response['results']:
	           label = "La tua posizione"
	           street =result['formatted_address']
	           mapitem = MapItem(label=label, street=street, latitude=latitude, longitude=longitude)
	           googleplaces_results.append(mapitem)
	           mapsnippet = MapItemSnippet(items=googleplaces_results)
	           view = AddViews(self.refId, dialogPhase="Completion")
	           view.views = [AssistantUtteranceView(speakableText='Mostro la tua posizione sulla mappa...', dialogIdentifier="googlePlacesMap"), mapsnippet]
	           self.sendRequestWithoutAnswer(view)
	           self.complete_request()
	     else:
	       self.say("Scusa, non ti ho trovato...")
	       self.complete_request()

	@register("it-IT", ".*andamento del traffico (a) (?P<location>[\w ]+?)$")
	@register("en-GB", ".*traffic like (in|on) (?P<location>[\w ]+?)$")
	def traffic(self, speech, language, regex):
	   searchlocation = regex.group('location')
	   Title = searchlocation   
	   Query = urllib.quote_plus(str(Title.encode("utf-8")))
	   googleurl = "http://maps.googleapis.com/maps/api/geocode/json?address={0}&sensor=true&language=en".format(Query)
	   jsonString = urllib2.urlopen(googleurl, timeout=20).read()
	   response = json.loads(jsonString)
	   if (response['status'] == 'OK') and (len(response['results'])):
	     for result in response['results']:
	         label = "{0}".format(Title.title())
	         latitude=result['geometry']['location']['lat']
	         longitude=result['geometry']['location']['lng']
	         city=result['address_components'][0]['long_name']
	         state=result['address_components'][2]['short_name']
	         country=result['address_components'][3]['short_name']
	   code = 0
	   Loc = Location(self.refId)
	   Loc.street = ""
	   Loc.countryCode = country
	   Loc.city = city
	   Loc.latitude = latitude
	   Loc.stateCode = state
	   Loc.longitude = longitude
	   Map = MapItem(self.refId)
	   Map.detailType = "ADDRESS_ITEM"
	   Map.label = label
	   Map.location = Loc
	   Source = MapItem(self.refId)
	   Source.detailType = "CURRENT_LOCATION"
	   ShowPoints = ShowMapPoints(self.refId)
	   ShowPoints.showTraffic = True  
	   ShowPoints.showDirections = False
	   ShowPoints.regionOfInterestRadiusInMiles = "10.0"
	   ShowPoints.itemDestination = Map
	   ShowPoints.itemSource = Source
	   AddViews = UIAddViews(self.refId)
	   AddViews.dialogPhase = "Summary"
	   AssistantUtteranceView = UIAssistantUtteranceView()
	   AssistantUtteranceView.dialogIdentifier = "LocationSearch#foundLocationForTraffic"
	   AssistantUtteranceView.speakableText = "Questo e' il traffico:"
	   AssistantUtteranceView.text = "Questo e' il traffico:"
	   AddViews.views = [(AssistantUtteranceView)]
	   AddViews.scrollToTop = False
	   AddViews.callbacks = [ResultCallback([ShowPoints], code)]
	   callback = [ResultCallback([AddViews])]
	   self.complete_request(callbacks=[ResultCallback([AddViews], code)])

	@register("it-IT", ".*andamento del traffico")
	@register("en-GB", ".*traffic like")
	def trafficSelf(self, speech, language, regex):
	   mapGetLocation = self.getCurrentLocation(force_reload=True,accuracy=GetRequestOrigin.desiredAccuracyBest)
	   latitude= mapGetLocation.latitude
	   longitude= mapGetLocation.longitude
	   label = "La tua posizione"
	   code = 0
	   Loc = Location(self.refId)
	   Loc.street = ""
	   Loc.countryCode = "US"
	   Loc.city = ""
	   Loc.latitude = latitude
	   Loc.stateCode = ""
	   Loc.longitude = longitude
	   Map = MapItem(self.refId)
	   Map.detailType = "ADDRESS_ITEM"
	   Map.label = label
	   Map.location = Loc
	   Source = MapItem(self.refId)
	   Source.detailType = "CURRENT_LOCATION"
	   ShowPoints = ShowMapPoints(self.refId)
	   ShowPoints.showTraffic = True  
	   ShowPoints.showDirections = False
	   ShowPoints.regionOfInterestRadiusInMiles = "10.0"
	   ShowPoints.itemDestination = Map
	   ShowPoints.itemSource = Source
	   AddViews = UIAddViews(self.refId)
	   AddViews.dialogPhase = "Summary"
	   AssistantUtteranceView = UIAssistantUtteranceView()
	   AssistantUtteranceView.dialogIdentifier = "LocationSearch#foundLocationForTraffic"
	   AssistantUtteranceView.speakableText = "Questo Ë il traffico:"
	   AssistantUtteranceView.text = "Questo e' il traffico:"
	   AddViews.views = [(AssistantUtteranceView)]
	   AddViews.scrollToTop = False
	   AddViews.callbacks = [ResultCallback([ShowPoints], code)]
	   callback = [ResultCallback([AddViews])]
	   self.complete_request(callbacks=[ResultCallback([AddViews], code)])

	@register("it-IT", "(Come faccio ad andare( a)?|.*direzioni( a?)) ((?P<userlocation>(home|work|school))|(?P<location>[\w ]+))")
	@register("en-GB", "(How do I get( to)?|.*directions( to?)) ((?P<userlocation>(home|work|school))|(?P<location>[\w ]+))")
	def traffic(self, speech, language, regex):
	   if regex.group('userlocation'):
	       locationType = regex.group('userlocation').capitalize()
	       label = locationType.title()
	       if locationType == "Work" or locationType == "Home":
	           locationType = "_$!<{0}>!$_".format(locationType)
	       meSearch = ABPersonSearch(self.refId)
	       meSearch.me = True
	       meSearch.scope = "Local"
	       answer = self.getResponseForRequest(meSearch)
	       if ObjectIsCommand(answer, ABPersonSearchCompleted):
	           results = ABPersonSearchCompleted(answer)
	           persons = results.results
	           identfind = results.results[0]
	       contactIdentifier = identfind.identifier
	       me = persons[0]
	       Addresses = filter(lambda x: x.label == locationType, me.addresses)
	       if len(Addresses) > 0:
	           Result = Addresses[0]
	           street = Result.street
	           PostalCode = Result.postalCode
	           city = Result.city
	           Title = "{0}, {1}, {2}".format(street, city, PostalCode)
	           Query = urllib.quote_plus(str(Title.encode("utf-8")))
	           googleurl = "http://maps.googleapis.com/maps/api/geocode/json?address={0}&sensor=true".format(Query)
	           jsonString = urllib2.urlopen(googleurl, timeout=20).read()
	           response = json.loads(jsonString)
	           if (response['status'] == 'OK') and (len(response['results'])):
	               for result in response['results']:
	                   latitude=result['geometry']['location']['lat']
	                   longitude=result['geometry']['location']['lng']
	                   state=result['address_components'][4]['long_name']
	       else: 
	           self.say("Mi dispiace, non riuscivo a trovare {0} nella tua rubrica".format(label))
	           self.complete_request()
	   else:
	       searchlocation = regex.group('location')
	       Title = searchlocation   
	       Query = urllib.quote_plus(str(Title.encode("utf-8")))
	       googleurl = "http://maps.googleapis.com/maps/api/geocode/json?address={0}&sensor=true&language=en".format(Query)
	       jsonString = urllib2.urlopen(googleurl, timeout=20).read()
	       response = json.loads(jsonString)
	       label = Title.title()
	       if (response['status'] == 'OK') and (len(response['results'])):
	         response = response['results'][0]
	         label = "{0}".format(Title.title())
	         latitude=response['geometry']['location']['lat']
	         longitude=response['geometry']['location']['lng']
	         city=response['address_components'][0]['long_name']
	         state=response['address_components'][2]['short_name']
	         country="US"
	         street=""
	       else:
	         random_results = random.randint(2,15)
	         mapGetLocation = self.getCurrentLocation(force_reload=True,accuracy=GetRequestOrigin.desiredAccuracyBest)
	         latitude= mapGetLocation.latitude
	         longitude= mapGetLocation.longitude
	         yelpurl = "http://api.yelp.com/business_review_search?term={0}&lat={1}&long={2}&radius=10&limit=10&ywsid={3}".format(Query, latitude, longitude, yelp_api_key)
	         try:
	           jsonString = urllib2.urlopen(yelpurl, timeout=20).read()
	         except:
	           jsonString = None
	         if jsonString != None:
	           response = json.loads(jsonString)
	           if (response['message']['text'] == 'OK') and (len(response['businesses'])):
	               sortedResults = sorted(response['businesses'], key=lambda business: float(business['distance']))
	               response = response['businesses']
	               sortedResults = sortedResults[0]
	               label = sortedResults['name']
	               latitude = sortedResults['latitude']
	               longitude = sortedResults['longitude']
	               state = sortedResults['state']
	               street = sortedResults['address1']
	               city = sortedResults['city']
	           else:
	               self.say("Scusa non ho trovato alcun risultato per "+str(Title)+" vicino a te!")
	               self.complete_request()

	   code = 0
	   Loc = Location(self.refId)
	   Loc.street = street
	   Loc.countryCode = "US"
	   Loc.city = city
	   Loc.latitude = latitude
	   Loc.stateCode = state
	   Loc.longitude = longitude
	   Map = MapItem(self.refId)
	   Map.detailType = "ADDRESS_ITEM"
	   Map.label = label
	   Map.location = Loc
	   Source = MapItem(self.refId)
	   Source.detailType = "CURRENT_LOCATION"
	   ShowPoints = ShowMapPoints(self.refId)
	   ShowPoints.showTraffic = False  
	   ShowPoints.showDirections = True
	   ShowPoints.regionOfInterestRadiusInMiles = "10.0"
	   ShowPoints.itemDestination = Map
	   ShowPoints.itemSource = Source
	   AddViews = UIAddViews(self.refId)
	   AddViews.dialogPhase = "Summary"
	   AssistantUtteranceView = UIAssistantUtteranceView()
	   AssistantUtteranceView.dialogIdentifier = "LocationSearch#foundLocationForDirections"
	   AssistantUtteranceView.speakableText = "Questa Ë la direzione per {0}:".format(label)
	   AssistantUtteranceView.text = "Questa Ë la direzione per {0}:".format(label)
	   AddViews.views = [(AssistantUtteranceView)]
	   AddViews.scrollToTop = False
	   AddViews.callbacks = [ResultCallback([ShowPoints], code)]
	   callback = [ResultCallback([AddViews])]
	   self.complete_request(callbacks=[ResultCallback([AddViews], code)])
